Asset factory contract
cryptzon/assetbuilder pull request #10
Opened 2018-02-08 03:15 UTC by joaoaguiam

Refactorization of the Factory Smart Contract

**Registry**:
- _AssetTypesRegistry.sol:_  Keeps registry of the owners of each asset type

**Assets:**
- _AssetType.sol:_ Base contract of all asset types, contains a string indicating the type of asset. Using a string instead of an enum in order to easily extend the platform with new asset types without redeploying the main contracts
- _SimpleAssetType.sol:_ First asset type. Just a simple one with basic information.

**Factories:**
- _AssetTypeFactory.sol:_ Base contract for all type of factories. Manages the registering of assets in the registry.
- _SimpleAssetTypeFactory.sol:_ Factory contract to create SimpleAssets.

2018-02-08 05:45 UTC, mhagel requested changes
this can proceed when we make sure the node_modules files are not checked in

2018-02-08 14:50 UTC, mhagel commented
node_modules are still included. They were probably committed before the gitignore could stop them. You could delete the node_modules directory, and do another commit. Or I can do this for you. @joaoaguiam

2018-02-09 06:30 UTC, joaoaguiam commented
Removed the node_modules, can you please check again @mhagel ?

2018-02-09 14:05 UTC, mhagel approved these changes

2018-02-09 14:06 UTC, merged